### ISSUE TITLE
Huge and missing buttons

### ISSUE THREAD

**Issue by pryme-svg** [sainnhe/gruvbox-material-gtk#3]
![image](https://user-images.githubusercontent.com/65417452/100698049-63cf6780-334c-11eb-83c6-ea3c2ba711e0.png)

In pcmanfm, some of the tabs are also missing, like edit.

![image](https://user-images.githubusercontent.com/65417452/100698085-7ba6eb80-334c-11eb-93cf-c39117deb960.png)

**Comment by TheGreatMcPain** [comment]
I attempted to recreate this theme with oomox, and appearently when you export
the theme with the "Generate 2x scaled (HiDPI) assets for GTK+2" option the icons
will become larger, and sometimes won't render properly on lower DPI displays
(my display is 1080p with a dpi of 96) like in @pryme-svg's pictures.

I think it would be a good idea to make a seperate theme that doesn't have the HiDPI
option enabled.

**Comment by pryme-svg** [comment]
It doesn't seem like the maintainer of this repo is responding. You said you recreated it. Would you be willing to share?

**Comment by TheGreatMcPain** [comment]
It's probably not exact, but Here's the oomox color file.

[Gruvbox-Materia-Test](https://github.com/sainnhe/gruvbox-material-gtk/files/5693078/Gruvbox-Materia-Test.txt)

Just open up Oomox's gui and click "Import -> Oomox Colors File".

**Comment by sainnhe** [comment]
@pryme-svg 

> It doesn't seem like the maintainer of this repo is responding.

Coz I'm preparing for the postgraduate exam, so I don't have much time recently.

@TheGreatMcPain Would you like to maintain this project? I can add you as a collaborator or directly transfer this repo to you.

**Comment by TheGreatMcPain** [comment]
Sure I can help maintain it, just add me as a collaborator.

Also, could you send me a copy of your Oomox color file? It should be in `~/.config/oomox/colors`.

**Comment by sainnhe** [comment]
@TheGreatMcPain Done, check your github notification.

> Also, could you send me a copy of your Oomox color file?

I created a new branch named `config`, you can checkout this branch.

**Comment by TheGreatMcPain** [comment]
I just finished up making a commit where I've added a seperate high-DPI version of the theme.

Also, the original Oomox color file wasn't in the `config` branch, but I
was able to recreate the same look, so it's close enough.
