### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by mietinen** [sainnhe/gruvbox-material-gtk#7]
Would it be much trouble to update the icons using the latest Papirus icons? There are icons missing, example symbolic/devices/ram-symbolic.svg

**Comment by TheGreatMcPain** [comment]
I went ahead and re-exported the theme with the lastest version of oomox.

Looks like `symbolic/devices/ram-symbolic.svg` is in there now.

**Comment by TheGreatMcPain** [comment]
I'm gonna go ahead and close this.
